---
apiVersion: v1
kind: Secret
metadata:
  name: team-infrastructure
  namespace: team-automation
type: Opaque
data:
    #used for application-awx-config (values need to be base64encoded)
    git_username: ""
    git_access_token: ""
    awx_development_access_token: ""
    awx_staging_access_token: ""
    awx_production_access_token: ""
    #used for service-api-automation_orchestration (values need to be base64encoded)
    awx_host: ""
    awx_env: ""
...
---
apiVersion: v1
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJodHRwczovL2FiY29udGFpbmVycmVnLmFtZXJpc291cmNlYmVyZ2VuLmNvbS8iOnsidXNlcm5hbWUiOiJhMTI3NjkyIiwicGFzc3dvcmQiOiJAc1QwbjU5Mjc1MjIiLCJlbWFpbCI6ImFzdG9uLmNyYWRkb2NrQGFtZXJpc291cmNlYmVyZ2VuLmNvbSIsImF1dGgiOiJZVEV5TnpZNU1qcEFjMVF3YmpVNU1qYzFNakk9In19fQ=="
kind: Secret
metadata:
  name: harbor-cred
  namespace: team-automation
type: kubernetes.io/dockerconfigjson
...
